### ISSUE TITLE
depends: add farming

### ISSUE THREAD

**Issue by paramat** [Ezhh/fireflies#1]
For bugnet string.

**Comment by Ezhh** [comment]
It's only in a recipe, so my understanding was it's not actually needed? Please let me know if I'm wrong.

I try to be as open as possible with depends because not everyone might have the same use case for a mod (creative players don't need recipes, for example).

**Comment by paramat** [comment]
Hm good point, it's probably ok as it is then, feel free to close.

**Comment by Ezhh** [comment]
Realised I'm being inconsistent, because I did add vessels even though that's also only in a recipe (I think it's because I used the vessels texture directly while starting out, before making the animated one). Should either add farming or remove vessels. 

Since you are considering this for MTG, is there a precedent one way or the other for inclusion of mods that are just used in recipes?

**Comment by paramat** [comment]
I would assume that some players would not be interested in catching the fireflies, in which case there's no need to insist on farming or vessels. But if those mods are present they should be loaded first to provide the crafting materials, so add them as optional dependencies i guess.

**Comment by Ezhh** [comment]
I think for recipes it doesn't matter, but it sounds like a good approach, since optional is what they are. :)

**Comment by paramat** [comment]
Tested, you're right there's no need for any sort of dependency on vessels or farming. Personally i would not add them as any kind of dependency.

**Comment by Ezhh** [comment]
Removed vessels from depends.

**Comment by Ezhh** [comment]
Actually... I have just realised I will need to add this back in, since I'm going to allow fireflies to be released from bottles as per #4.

Not having vessels would lead to unknown nodes at this point, so even though it won't crash the game, it would be very poor to run this mod without vessels.
