### ISSUE TITLE
Optimise textures

### ISSUE THREAD

**Issue by Ezhh** [Ezhh/fireflies#2]
Reminder to myself (or to anyone who feels like opening a PR sooner than I do).

**Comment by paramat** [comment]
The free animated firefly texture has a colour profile that is known to cause warnings, best to 'assign' the default and standard 'RGB workspace (sRGB built-in)' colour profile for all textures (and of course convert all to indexed colour).

**Comment by Ezhh** [comment]
@paramat Could you have a look at the current textures please, and maybe make any final changes needed?

**Comment by paramat** [comment]
Now doing, will correct colour profile.

**Comment by paramat** [comment]
Just downloaded and checked them all, they actually all have the correct colour profile.
Earlier i probably did something wrong by saving the images from a github page.

**Comment by Ezhh** [comment]
I updated them since you first checked, but wasn't sure if I had done so correctly (I'm working with PhotoShop, not Gimp, so different options), but you'd have been right before either way. :) 

Thanks for checking.
