### ISSUE TITLE
Bottle brightness

### ISSUE THREAD

**Issue by Fixer-007** [Ezhh/fireflies#3]
Right now bottle with firefly is ridiculously bright, it should have the same low brightness as firefly without bottle.

**And then comes nice idea, by catching more fireflies bottle becomes progressively more brighter.** 
So you can have very configurable light source.

**Comment by Ezhh** [comment]
I disagree that it's "ridiculously bright". Will likely fine tune a bit, but if it's too little light, it pointless.

**Comment by paramat** [comment]
Torches are 12 so how about a little lower than 12? Realism would be useless as a light source.

**Comment by Ezhh** [comment]
I've set fireflies themselves to 6, which seems nice when walking between them, so I don't want to change that value. For the bottles, I am thinking to test either 9 or 10 to see how that looks.

**Comment by paramat** [comment]
Yes my suggestion is for the bottle light source, certainly should be less than 12 so torches retain their advantage.

**Comment by Ezhh** [comment]
9 looks okay when I test, so changed to that.
