### ISSUE TITLE
More frames

### ISSUE THREAD

**Issue by Ezhh** [Ezhh/fireflies#5]
paramat suggested using a 32 frame animation for more vertical movement and movement complexity.

**Comment by paramat** [comment]
Oops i just saw you have 8 frames currently, i assumed it was 16.
I suggest roughly 16, 32 is a lot.

**Comment by Ezhh** [comment]
I was wondering. I'm honestly not sure how much more frames will help. We have two issues:
- Horizontal movement is a no, since a plantlike drawtype will separate the two visible parts when they pull away from the center. And I also think it would draw more attention to the movement of each firefly being the same, not different/random. (I know you haven't suggested horizontal, but just covering it for anyone else following this as well).
- More vertical movement might be nice; however then we're going to have selection box issues. Right now the lower and upper limits of movement are matched to the selection box, which I wanted to keep as small as possible. There's no way to make the selection box move, and if it gets much larger it could get in the way of targeting other things behind the firefly node, when it seems you should be able to target them.

**Comment by paramat** [comment]
The movement can still be confined to a small height, but be a more complex motion with several up-and-downs per cycle to be less repetitive. Personally i'm not too bothered by the firefly moving a slightly outside its selectionbox.

**Comment by Ezhh** [comment]
So same range, but not using the full extent of it each time it changes direction?

**Comment by paramat** [comment]
Yeah or whatever, bug-like motion :)

**Comment by Ezhh** [comment]
Will play about with it some more.

**Comment by Ezhh** [comment]
Not happy with any tests, so leaving as is for now.

**Comment by paramat** [comment]
Which is fine by me.
